"""initial snapshot after reset

Revision ID: 17096a328758
Revises: 
Create Date: 2025-07-04 18:50:45.482614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17096a328758'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'classroom_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('classroom_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'courses', 'classrooms', ['classroom_id'], ['id'])
    # ### end Alembic commands ###
